--Aydara TPV 16.1.01
ALTER TABLE dbo.FAMILIASARTICULOS ADD CtaVentas nvarchar(10) NULL, CtaCompras nvarchar(10) NULL
GO
UPDATE FAMILIASARTICULOS SET CtaVentas=''
UPDATE FAMILIASARTICULOS SET CtaCompras=''