ALTER TABLE dbo.HISTORICO_TICKETS ADD Exportado bit NULL
GO

ALTER TABLE dbo.HISTORICO_TICKETS ADD CONSTRAINT DF_HISTORICO_TICKETS_Exportado DEFAULT 0 FOR Exportado
GO

UPDATE HISTORICO_TICKETS SET Exportado=0
