CREATE TABLE dbo.INCIDENCIAS
	(
	IDIncidencia int NOT NULL IDENTITY (1, 1),
	TipoID int NOT NULL,
	Fecha datetime NULL,
	OperarioID int NOT NULL,
	Comentario text NULL,
	Cantidad decimal(18, 2) NULL,
	ArticuloID int NOT NULL,
	AfectaStock bit NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.INCIDENCIAS ADD CONSTRAINT
	PK_INCIDENCIAS PRIMARY KEY CLUSTERED 
	(
	IDIncidencia
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

CREATE TABLE dbo.INCIDENCIAS_TIPOS
	(
	IDTipo int NOT NULL,
	Descripcion nvarchar(50) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.INCIDENCIAS_TIPOS ADD CONSTRAINT
	PK_INCIDENCIAS_TIPOS PRIMARY KEY CLUSTERED 
	(
	IDTipo
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

INSERT INTO INCIDENCIAS_TIPOS (IDTipo, Descripcion) VALUES (1, 'Rotura')
INSERT INTO INCIDENCIAS_TIPOS (IDTipo, Descripcion) VALUES (2, 'Robo')
INSERT INTO INCIDENCIAS_TIPOS (IDTipo, Descripcion) VALUES (3, 'Defectuoso')
INSERT INTO INCIDENCIAS_TIPOS (IDTipo, Descripcion) VALUES (4, 'Dif. Inventario')
INSERT INTO INCIDENCIAS_TIPOS (IDTipo, Descripcion) VALUES (5, 'Otros')
GO

ALTER TABLE dbo.INCIDENCIAS ADD CONSTRAINT
	FK_INCIDENCIAS_INCIDENCIAS_TIPOS FOREIGN KEY
	(
	TipoID
	) REFERENCES dbo.INCIDENCIAS_TIPOS
	(
	IDTipo
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.INCIDENCIAS ADD CONSTRAINT
	FK_INCIDENCIAS_OPERARIOS FOREIGN KEY
	(
	OperarioID
	) REFERENCES dbo.OPERARIOS
	(
	Codigo
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.INCIDENCIAS ADD CONSTRAINT
	FK_INCIDENCIAS_ARTICULOS FOREIGN KEY
	(
	ArticuloID
	) REFERENCES dbo.ARTICULOS
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
