--Aydara TPV 15.10.01
ALTER TABLE TICKETS_LINEAS ADD [Peso] [decimal](18, 4) NULL
GO
ALTER TABLE HISTORICO_TICKETS_LINEAS ADD [Peso] [decimal](18, 4) NULL
GO
ALTER TABLE HISTORICO_TICKETS_ANULADOS_LINEAS ADD [Peso] [decimal](18, 4) NULL