--Aydara TPV 17.10.01
ALTER TABLE ARTICULOS ALTER COLUMN Descripcion nvarchar(150) NULL
GO
ALTER TABLE TICKETS_LINEAS ALTER COLUMN DescripcionArticulo nvarchar(150) NULL
GO
ALTER TABLE HISTORICO_TICKETS_LINEAS ALTER COLUMN DescripcionArticulo nvarchar(150) NULL
GO
ALTER TABLE HISTORICO_TICKETS_ANULADOS_LINEAS ALTER COLUMN DescripcionArticulo nvarchar(150) NULL
GO
ALTER TABLE CLIENTES ALTER COLUMN NombreFiscal nvarchar(150) NULL
GO
ALTER TABLE CLIENTES ALTER COLUMN Direccion nvarchar(150) NULL
GO
ALTER TABLE CLIENTES ALTER COLUMN CodigoPostal nvarchar(10) NULL
GO
ALTER TABLE CLIENTES ALTER COLUMN Poblacion nvarchar(150) NULL
GO
ALTER TABLE CLIENTES ALTER COLUMN Provincia nvarchar(150) NULL
GO
ALTER TABLE CLIENTES ALTER COLUMN TelParticular nvarchar(50) NULL
GO
ALTER TABLE CLIENTES ALTER COLUMN TelMovil nvarchar(50) NULL
GO
ALTER TABLE CLIENTES ALTER COLUMN Email nvarchar(150) NULL
GO
ALTER TABLE CLICREDI ADD TelParticular nvarchar(50) NULL
GO
ALTER TABLE CLICREDI ADD TelMovil nvarchar(50) NULL
GO
ALTER TABLE CLICREDI ADD Email nvarchar(150) NULL
GO
ALTER TABLE CLICREDI ADD CuentaExt nvarchar(50) NULL
GO
ALTER TABLE CLICREDI ADD DescCar1 nvarchar(50) NULL
GO
ALTER TABLE TRASPASO_ALMACENES ADD FechaEnvio datetime NULL