'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ScriptsBD
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AydaraTPV.ScriptsBD", GetType(ScriptsBD).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a /****** Object:  Table [dbo].[ACTIVACIONES]    Script Date: 07/23/2013 14:28:33 ******/
        '''IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[ACTIVACIONES]&apos;) AND type in (N&apos;U&apos;))
        '''DROP TABLE [dbo].[ACTIVACIONES]
        '''GO
        '''/****** Object:  Table [dbo].[ALBARANES_COMPRAS]    Script Date: 07/23/2013 14:28:33 ******/
        '''IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[ALBARANES_COMPRAS]&apos;) AND type in (N&apos;U&apos;))
        '''DROP TABLE [dbo].[ALBARANES_COMPRAS]
        '''GO
        '''/****** Object:  Tabl [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property BBDD_Alimentacion() As String
            Get
                Return ResourceManager.GetString("BBDD_Alimentacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a /****** Object:  Table [dbo].[ACTIVACIONES]    Script Date: 07/23/2013 14:28:33 ******/
        '''IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[ACTIVACIONES]&apos;) AND type in (N&apos;U&apos;))
        '''DROP TABLE [dbo].[ACTIVACIONES]
        '''GO
        '''/****** Object:  Table [dbo].[ALBARANES_COMPRAS]    Script Date: 07/23/2013 14:28:33 ******/
        '''IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[ALBARANES_COMPRAS]&apos;) AND type in (N&apos;U&apos;))
        '''DROP TABLE [dbo].[ALBARANES_COMPRAS]
        '''GO
        '''/****** Object:  Tabl [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property BBDD_TallasColores() As String
            Get
                Return ResourceManager.GetString("BBDD_TallasColores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a USE [master]
        '''GO
        '''/****** Object:  Database [AydaraTPV_NAVAL]    Script Date: 19/09/2017 8:43:25 ******/
        '''CREATE DATABASE [AydaraTPV_NAVAL]
        ''' CONTAINMENT = NONE
        ''' ON  PRIMARY 
        '''( NAME = N&apos;AydaraTPV_NAVAL&apos;, FILENAME = N&apos;C:\Program Files\Microsoft SQL Server\MSSQL12.A3ERP\MSSQL\DATA\AydaraTPV_NAVAL.mdf&apos; , SIZE = 6144KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
        ''' LOG ON 
        '''( NAME = N&apos;AydaraTPV_NAVAL_log&apos;, FILENAME = N&apos;C:\Program Files\Microsoft SQL Server\MSSQL12.A3ERP\MSSQL\DATA\AydaraTPV_NAVAL_log.ldf&apos; , S [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property BBDD_Vacia() As String
            Get
                Return ResourceManager.GetString("BBDD_Vacia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 13.1.01
        '''ALTER TABLE TICKETS ADD CierreTurno BIT
        '''ALTER TABLE HISTORICO_TICKETS ADD CierreTurno BIT
        '''ALTER TABLE MOVIMIENTOS_CAJA ADD CierreTurno BIT.
        '''</summary>
        Friend Shared ReadOnly Property sql_1() As String
            Get
                Return ResourceManager.GetString("sql_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 13.1.18
        '''CREATE TABLE [dbo].[PARAMETROS_BASCULA](
        '''	[Prefijo] [nchar](2) COLLATE Modern_Spanish_CI_AS NOT NULL,
        '''	[PosInicial_Articulo] [int] NULL,
        '''	[PosFinal_Articulo] [int] NULL,
        '''	[PosInicial_Peso] [int] NULL,
        '''	[PosFinal_Peso] [int] NULL,
        '''	[PosInicial_Importe] [int] NULL,
        '''	[PosFinal_Importe] [int] NULL,
        ''' CONSTRAINT [PK_PARAMETROS_BASCULA] PRIMARY KEY CLUSTERED 
        '''(
        '''	[Prefijo] ASC
        ''')WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
        ''') ON [PRIMARY]
        '''.
        '''</summary>
        Friend Shared ReadOnly Property sql_10() As String
            Get
                Return ResourceManager.GetString("sql_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 13.2.01
        '''CREATE TABLE [dbo].[ACTIVACIONES](
        '''	[NumeroSerie] [nvarchar](50) NOT NULL,
        '''	[NombreEquipo] [nvarchar](50) NULL,
        '''	[CodigoActivacion] [nvarchar](50) NULL,
        '''	[FechaInstalacion] [ntext] NULL,
        '''	[FechaCaducidad] [ntext] NULL,
        ''' CONSTRAINT [PK_NumerosSerie] PRIMARY KEY CLUSTERED 
        '''(
        '''	[NumeroSerie] ASC
        ''')WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ''') ON [PRIMARY] TEXTIMAGE_ON [PRIMARY].
        '''</summary>
        Friend Shared ReadOnly Property sql_11() As String
            Get
                Return ResourceManager.GetString("sql_11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 14.1.01
        '''ALTER TABLE EXISTENCIAS ALTER COLUMN ExistenciaInicial decimal(18,4)
        '''
        '''GO
        '''
        '''ALTER TABLE EXISTENCIAS ALTER COLUMN ExistenciaActual decimal(18,4)
        '''
        '''GO
        '''
        '''ALTER TABLE INVENTARIO ALTER COLUMN Cantidad decimal(18,4).
        '''</summary>
        Friend Shared ReadOnly Property sql_12() As String
            Get
                Return ResourceManager.GetString("sql_12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 14.1.07
        '''UPDATE TICKETS 
        '''SET ImporteEfectivo=ImporteTotal, ImporteCambios=0
        '''WHERE ImporteCambios&gt;99999
        '''
        '''UPDATE HISTORICO_TICKETS
        '''SET ImporteEfectivo=ImporteTotal, ImporteCambios=0
        '''WHERE ImporteCambios&gt;99999.
        '''</summary>
        Friend Shared ReadOnly Property sql_13() As String
            Get
                Return ResourceManager.GetString("sql_13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 15.1.01
        '''ALTER TABLE dbo.CLIENTES ADD Observaciones text NULL, Email nvarchar(100) NULL
        '''GO
        '''UPDATE CLIENTES SET Observaciones=&apos;&apos;
        '''UPDATE CLIENTES SET Email=&apos;&apos;.
        '''</summary>
        Friend Shared ReadOnly Property sql_14() As String
            Get
                Return ResourceManager.GetString("sql_14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 16.1.01
        '''ALTER TABLE dbo.FAMILIASARTICULOS ADD CtaVentas nvarchar(10) NULL, CtaCompras nvarchar(10) NULL
        '''GO
        '''UPDATE FAMILIASARTICULOS SET CtaVentas=&apos;&apos;
        '''UPDATE FAMILIASARTICULOS SET CtaCompras=&apos;&apos;.
        '''</summary>
        Friend Shared ReadOnly Property sql_15() As String
            Get
                Return ResourceManager.GetString("sql_15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ALTER TABLE dbo.HISTORICO_TICKETS ADD Exportado bit NULL
        '''GO
        '''
        '''ALTER TABLE dbo.HISTORICO_TICKETS ADD CONSTRAINT DF_HISTORICO_TICKETS_Exportado DEFAULT 0 FOR Exportado
        '''GO
        '''
        '''UPDATE HISTORICO_TICKETS SET Exportado=0
        '''.
        '''</summary>
        Friend Shared ReadOnly Property sql_16() As String
            Get
                Return ResourceManager.GetString("sql_16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ALTER TABLE dbo.TIENDAS ADD DtoSobreTarifa decimal(18, 2) NULL, DtoSobrePromocion decimal(18, 2) NULL
        '''GO
        '''
        '''UPDATE TIENDAS SET DtoSobreTarifa=0
        '''UPDATE TIENDAS SET DtoSobrePromocion=0
        '''.
        '''</summary>
        Friend Shared ReadOnly Property sql_17() As String
            Get
                Return ResourceManager.GetString("sql_17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ALTER TABLE dbo.TIENDAS ADD RecibePromociones bit NULL, ActualizaCosto bit NULL
        '''GO
        '''
        '''UPDATE TIENDAS SET RecibePromociones=1
        '''UPDATE TIENDAS SET ActualizaCosto=0
        '''.
        '''</summary>
        Friend Shared ReadOnly Property sql_18() As String
            Get
                Return ResourceManager.GetString("sql_18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CREATE TABLE dbo.INCIDENCIAS
        '''	(
        '''	IDIncidencia int NOT NULL IDENTITY (1, 1),
        '''	TipoID int NOT NULL,
        '''	Fecha datetime NULL,
        '''	OperarioID int NOT NULL,
        '''	Comentario text NULL,
        '''	Cantidad decimal(18, 2) NULL,
        '''	ArticuloID int NOT NULL,
        '''	AfectaStock bit NULL
        '''	)  ON [PRIMARY]
        '''	 TEXTIMAGE_ON [PRIMARY]
        '''GO
        '''ALTER TABLE dbo.INCIDENCIAS ADD CONSTRAINT
        '''	PK_INCIDENCIAS PRIMARY KEY CLUSTERED 
        '''	(
        '''	IDIncidencia
        '''	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = O [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property sql_19() As String
            Get
                Return ResourceManager.GetString("sql_19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV  13.1.01
        '''ALTER TABLE TIENDAS ADD NumeroAlbaran INT.
        '''</summary>
        Friend Shared ReadOnly Property sql_2() As String
            Get
                Return ResourceManager.GetString("sql_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a /****** Object:  Table [dbo].[HISTORICO_TICKETS_ANULADOS]    Script Date: 06/11/2015 14:28:25 ******/
        '''IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[HISTORICO_TICKETS_ANULADOS]&apos;) AND type in (N&apos;U&apos;))
        '''DROP TABLE [dbo].[HISTORICO_TICKETS_ANULADOS]
        '''GO
        '''/****** Object:  Table [dbo].[HISTORICO_TICKETS_LINEAS]    Script Date: 06/11/2015 14:28:24 ******/
        '''IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[HISTORICO_TICKETS_ANULADOS_LINEAS]&apos;) AND type in (N&apos;U&apos;)) [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property sql_20() As String
            Get
                Return ResourceManager.GetString("sql_20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ALTER TABLE dbo.TIENDAS ADD AlbaranFormatoTicket bit NULL, AlbaranFormatoA4 bit NULL
        '''GO
        '''
        '''UPDATE TIENDAS SET AlbaranFormatoTicket=1, AlbaranFormatoA4=1.
        '''</summary>
        Friend Shared ReadOnly Property sql_21() As String
            Get
                Return ResourceManager.GetString("sql_21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CREATE TABLE [dbo].[REFERENCIAS_PROVEEDORES](
        '''	[Articulo_Id] [int] NOT NULL,
        '''	[CodigoProveedor] [int] NOT NULL,
        '''	[Referencia] [nvarchar](50) NULL,
        '''	[PrecioCoste] [decimal](18, 4) NULL,
        '''	[PrecioVenta] [decimal](18, 4) NULL,
        '''	[UnidadesCaja] [int] NULL,
        ''' CONSTRAINT [PK_REFERENCIAS_PROVEEDORES] PRIMARY KEY CLUSTERED 
        '''(
        '''	[Articulo_Id] ASC,
        '''	[CodigoProveedor] ASC
        ''')WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ''') ON [ [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property sql_22() As String
            Get
                Return ResourceManager.GetString("sql_22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 15.7.02
        '''ALTER TABLE INCIDENCIAS ADD [PrecioCoste] [decimal](18, 4) NULL
        '''GO
        '''UPDATE INCIDENCIAS SET PrecioCoste = 0.
        '''</summary>
        Friend Shared ReadOnly Property sql_23() As String
            Get
                Return ResourceManager.GetString("sql_23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 15.10.01
        '''ALTER TABLE TICKETS_LINEAS ADD [Peso] [decimal](18, 4) NULL
        '''GO
        '''ALTER TABLE HISTORICO_TICKETS_LINEAS ADD [Peso] [decimal](18, 4) NULL
        '''GO
        '''ALTER TABLE HISTORICO_TICKETS_ANULADOS_LINEAS ADD [Peso] [decimal](18, 4) NULL.
        '''</summary>
        Friend Shared ReadOnly Property sql_24() As String
            Get
                Return ResourceManager.GetString("sql_24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 15.10.02
        '''ALTER TABLE TIENDAS ADD [Comunicaciones_Terminales] [nvarchar](max) NULL
        '''GO
        '''UPDATE TIENDAS SET Comunicaciones_Terminales = &apos;&apos;.
        '''</summary>
        Friend Shared ReadOnly Property sql_25() As String
            Get
                Return ResourceManager.GetString("sql_25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 15.12.01
        '''ALTER PROCEDURE [dbo].[CrearTablaTemporal_Promociones]
        '''AS
        '''      
        '''SET NOCOUNT ON
        '''
        '''IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[COMUNICACIONES_PROMOCIONES]&apos;) AND type in (N&apos;U&apos;))
        '''DROP TABLE [dbo].[COMUNICACIONES_PROMOCIONES]
        '''
        '''CREATE TABLE [dbo].[COMUNICACIONES_PROMOCIONES](
        '''      [Id] [int] IDENTITY(1,1) NOT NULL,
        '''      [CodigoTienda] [int] NULL,
        '''      [CodigoArticulo] [nvarchar](7) COLLATE Modern_Spanish_CI_AS NULL,
        '''      [CodigoColor] [int] NUL [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property sql_26() As String
            Get
                Return ResourceManager.GetString("sql_26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 16.01.06
        '''ALTER TABLE PEDIDOS ADD [FechaEnvio] [datetime] NULL
        '''.
        '''</summary>
        Friend Shared ReadOnly Property sql_27() As String
            Get
                Return ResourceManager.GetString("sql_27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 16.04.01
        '''ALTER TABLE TIENDAS ADD VentaCredito bit NULL, ControlTarjetas bit NULL, EtiquetaElectronica bit NULL, NumeroFactura1 int NULL, NumeroFactura2 int NULL, Comunicaciones_DirectorioFicheros nvarchar(max) NULL
        '''
        '''GO
        '''
        '''UPDATE TIENDAS SET EtiquetaElectronica = 0, ControlTarjetas = 0, NumeroFactura1 = 0, NumeroFactura2 = 0, Comunicaciones_DirectorioFicheros = &apos;&apos;
        '''
        '''GO
        '''
        '''ALTER TABLE ARTICULOS ADD CodigoBascula nvarchar(2) NULL, PLU int NULL, DtoFidelizacion decimal(18,4) NULL, 
        '''EE_CodigoBa [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property sql_28() As String
            Get
                Return ResourceManager.GetString("sql_28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CREATE PROCEDURE [dbo].[ImportarArticulos] (@FicheroSEQ AS varchar(2500))
        '''AS
        '''BEGIN
        '''
        '''	SET NOCOUNT ON;
        '''
        '''DROP TABLE [dbo].[SEQ_ARTICULO]
        '''
        '''CREATE TABLE [dbo].[SEQ_ARTICULO](
        '''	[Codigo] [varchar](50) NULL,
        '''	[Descripcion] [varchar](150) NULL,
        '''	[TipoIva] [numeric](18, 0) NULL,
        '''	[CodigoFamilia] [varchar](50) NULL,
        '''	[CodigoSubfamilia] [varchar](50) NULL,
        '''	[CodigoProveedor] [numeric](18, 0) NULL,
        '''	[CodigoEnvase] [varchar](50) NULL,
        '''	[ControlEtiquetas] [varchar](50) NULL,
        '''	[CantidadVariable] [varchar]( [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property sql_29() As String
            Get
                Return ResourceManager.GetString("sql_29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV  13.1.01
        '''UPDATE TIENDAS SET NumeroAlbaran=0.
        '''</summary>
        Friend Shared ReadOnly Property sql_3() As String
            Get
                Return ResourceManager.GetString("sql_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 16.05.01
        '''ALTER TABLE TIENDAS ADD DirectorioFicheroBasculas nvarchar(max) NULL, EE_DireccionFTP nvarchar(max) NULL, EE_UsuarioFTP nvarchar(max) NULL, EE_PasswordFTP nvarchar(max) NULL
        '''
        '''GO
        '''
        '''UPDATE TIENDAS SET DirectorioFicheroBasculas = &apos;&apos;, EE_DireccionFTP = &apos;&apos;, EE_UsuarioFTP = &apos;&apos;, EE_PasswordFTP = &apos;&apos;.
        '''</summary>
        Friend Shared ReadOnly Property sql_30() As String
            Get
                Return ResourceManager.GetString("sql_30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 16.06.01
        '''ALTER TABLE TIENDAS ADD RegistroMercantil nvarchar(max) NULL
        '''
        '''GO
        '''
        '''UPDATE TIENDAS SET RegistroMercantil = &apos;&apos;.
        '''</summary>
        Friend Shared ReadOnly Property sql_31() As String
            Get
                Return ResourceManager.GetString("sql_31", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 16.06.01
        '''ALTER TABLE TICKETS ADD TotalRecargo decimal(18, 2) NULL, TotalDtoPP decimal(18, 2) NULL
        '''
        '''GO
        '''
        '''UPDATE TICKETS SET TotalRecargo = 0, TotalDtoPP = 0
        '''
        '''GO
        '''
        '''ALTER TABLE HISTORICO_TICKETS ADD TotalRecargo decimal(18, 2) NULL, TotalDtoPP decimal(18, 2) NULL
        '''
        '''GO
        '''
        '''UPDATE HISTORICO_TICKETS SET TotalRecargo = 0, TotalDtoPP = 0
        '''
        '''GO
        '''
        '''ALTER TABLE HISTORICO_TICKETS_ANULADOS ADD TotalRecargo decimal(18, 2) NULL, TotalDtoPP decimal(18, 2) NULL
        '''
        '''GO
        '''
        '''UPDATE HISTORICO_TICKETS_ANULADOS  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property sql_32() As String
            Get
                Return ResourceManager.GetString("sql_32", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 16.06.01
        '''ALTER TABLE ARTICULOS ADD ImporteEcoraee decimal(18, 4) NULL, Equivalencia decimal(18, 4) NULL
        '''GO
        '''UPDATE ARTICULOS SET ImporteEcoraee = 0, Equivalencia = 0
        '''
        '''GO
        '''
        '''ALTER TABLE CLIENTES ADD Matricula varchar(20) NULL, Marca varchar(50) NULL, Modelo varchar(50) NULL
        '''GO
        '''UPDATE CLIENTES SET Matricula = &apos;&apos;, Marca = &apos;&apos;, Modelo = &apos;&apos;
        '''
        '''GO
        '''
        '''ALTER TABLE TICKETS ADD Km decimal(18, 2) NULL
        '''GO
        '''UPDATE TICKETS SET Km = 0
        '''GO
        '''ALTER TABLE HISTORICO_TICKETS ADD Km decimal(18, 2) NULL
        '''GO
        '''UP [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property sql_33() As String
            Get
                Return ResourceManager.GetString("sql_33", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 17.10.01
        '''ALTER TABLE INCIDENCIAS ADD FechaCierre datetime NULL
        '''.
        '''</summary>
        Friend Shared ReadOnly Property sql_34() As String
            Get
                Return ResourceManager.GetString("sql_34", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 17.10.01
        '''ALTER TABLE INCIDENCIAS ADD FechaCierre datetime NULL
        '''.
        '''</summary>
        Friend Shared ReadOnly Property sql_35() As String
            Get
                Return ResourceManager.GetString("sql_35", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 13.1.03
        '''ALTER TABLE ARTICULOS ADD TpvTactil BIT
        '''ALTER TABLE ARTICULOS ALTER COLUMN Etiqueta NVARCHAR(20).
        '''</summary>
        Friend Shared ReadOnly Property sql_4() As String
            Get
                Return ResourceManager.GetString("sql_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV  13.1.07
        '''ALTER TABLE TICKETS ADD NumeroAlbaran INT
        '''ALTER TABLE HISTORICO_TICKETS ADD NumeroAlbaran INT.
        '''</summary>
        Friend Shared ReadOnly Property sql_5() As String
            Get
                Return ResourceManager.GetString("sql_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV  13.1.10
        '''ALTER TABLE CLIENTES ADD AlbaranCredito BIT.
        '''</summary>
        Friend Shared ReadOnly Property sql_6() As String
            Get
                Return ResourceManager.GetString("sql_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV  13.1.10
        '''ALTER PROCEDURE [dbo].[CrearTablaTemporal_Clientes]
        '''AS	
        '''SET NOCOUNT ON
        '''IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[CLIENTES]&apos;) AND type in (N&apos;U&apos;))
        '''DROP TABLE [dbo].[COMUNICACIONES_CLIENTES]
        '''CREATE TABLE [dbo].[COMUNICACIONES_CLIENTES](
        '''	[Id] [int] IDENTITY(1,1) NOT NULL,
        '''	[Codigo] [int] NOT NULL,
        '''	[NombreFiscal] [nvarchar](50) COLLATE Modern_Spanish_CI_AS NULL,
        '''	[Direccion] [nvarchar](50) COLLATE Modern_Spanish_CI_AS NULL,
        '''	[CodigoPostal] [nvar [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property sql_7() As String
            Get
                Return ResourceManager.GetString("sql_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV  13.1.11
        '''ALTER PROCEDURE [dbo].[CrearTablaTemporal_Articulos]
        '''AS
        '''	SET NOCOUNT ON;
        '''
        '''	IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[COMUNICACIONES_ARTICULOS]&apos;) AND type in (N&apos;U&apos;))
        '''	DROP TABLE [dbo].[COMUNICACIONES_ARTICULOS]
        '''
        '''	CREATE TABLE [dbo].[COMUNICACIONES_ARTICULOS](
        '''		[Id] [int] IDENTITY(1,1) NOT NULL,
        '''		[Codigo] [nvarchar](7) COLLATE Modern_Spanish_CI_AS NOT NULL,
        '''		[Descripcion] [nvarchar](50) COLLATE Modern_Spanish_CI_AS NULL,
        '''		[TipoIva] [int] N [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property sql_8() As String
            Get
                Return ResourceManager.GetString("sql_8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --Aydara TPV 13.1.13
        '''ALTER TABLE FAMILIASARTICULOS ADD TpvTactil BIT
        '''GO
        '''UPDATE FAMILIASARTICULOS SET TpvTactil = CASE WHEN Etiqueta&lt;&gt;&apos;&apos; THEN 1 ELSE 0 END.
        '''</summary>
        Friend Shared ReadOnly Property sql_9() As String
            Get
                Return ResourceManager.GetString("sql_9", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
